### ISSUE TITLE
Github Pages Deployment

### ISSUE THREAD

**Issue by xdega** [Flutter-Bounty-Hunters/static_shock#166]
Hey. So. Still loving the tool, but I encountered some challenges with Github Pages deployment that I would like to share.

### First Issue
The configuration outlined in the documentation ([https://staticshock.io/guides/deploy-to-github-pages/](https://staticshock.io/guides/deploy-to-github-pages/)) is deprecated.

My current build configuration that "works" is:

```yaml
name: Build and deploy website
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup a Dart environment
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      # Download all the packages that the app uses
      - run: dart pub get

      # Build the static site
      - run: dart run bin/main.dart

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Zip and upload the static site.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Replace the following with the local repository path
          # to your Static Shock build directory.
          path: ./build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

While this fixed my prior deployment issues (which had multiple deprecation warnings), I would be hesitant to update the documentation until I can clarify and resolve my next issue...

### Second Issue

My CSS is not being found (404). I have tried with/without relative paths, neither seem to work. 

If this is related to https://github.com/Flutter-Bounty-Hunters/static_shock/issues/50, I fear that this could mean I need to implement hacky workarounds to make this work locally and live alike. Do you have any guidance on this?

Here's my current blog website for reference: https://github.com/xdega/liamhockley_blog.github.io

Let me know if I am doing something really wrong. I don't want to continue iterating on the project until I get this initial issue resolved.

Thanks.
