### ISSUE TITLE
[Docs] Document all frontmatter properties

### ISSUE THREAD

**Issue by dkbast** [Flutter-Bounty-Hunters/static_shock#199]
Right now its difficult to figure out whats possible to do out of the box and where the user might need to write a custom plugin or tweak the HTML. 

It would be great to have a comprehensive list of all the frontmatter attributes that are currently supported.

Here is a list with what I've seen so far:

```yaml
title: My Blog Post
layout: layouts/blog-post.jinja
description: Why it matters more than ever to master the craft, even if it seems like AI is about to take over many of the day to day tasks.
publishDate: 2025-05-31
header: header.jpeg
basePath: /
draft: true
```
